### ISSUE TITLE
How to draw multiple rectangles in a row？

### ISSUE THREAD

**Issue by fanweiGit** [mircea21S/RichCanvas#10]
Hi, Is it possible to click the draw rectangle button once and then draw multiple rectangles in a row？
I tried to execute OnDrawCommand after the DrawEnded event, but it would result in not being able to select the drawn rectangle and occasionally there would be a drag instead of a draw rectangle.
Best Wishes!

**Comment by mircea21S** [comment]
Hi

You want to be able to draw multiple rectangles simultaneously? Or sequentially (one by one).

For multiple objects simultaneously this is not possible yet(should be a nice feature). If you want to draw them one by one you should just add multiple rectangles in the list, and when you finish drawing for one of them you should be able to click and draw the next one and so on.

For the drag part, dragging happens if your mouse is over the rectangle, maybe set ```IsDraggable``` to false and put it back to true when you're done with the action.

Thank you.

**Comment by fanweiGit** [comment]
Thank you for your detailed reply.
