### ISSUE TITLE
ScrollViewer scrollbar visibility not applied

### ISSUE THREAD

**Issue by Ygsildyr** [mircea21S/RichCanvas#19]
In our use case, we'd like to hide the scrollbars of the ScrollViewer in the RichItemsControl. We are using:
ScrollViewer.VerticalScrollBarVisibility="Hidden" ScrollViewer.HorizontalScrollBarVisibility="Hidden" properties.

These unfortunately do nothing yet. Is there anything we're missing?

**Comment by mircea21S** [comment]
Hi

There's an existing `DependencyProperty` on `RichItemsControl`, `DisableScroll` which is disabling the scroll.That's hiding the scrollbars, but you will lose scrolling functionality like mouse wheel scroll, auto-panning and so on.
I will also push some fixes regarding `DisableScroll`, because right now it's not updating the UI when the value is changed.

If you need to just hide the scrollbars and keep the whole scrolling logic, that's not possible right now, as I am explicitly setting the scrollbar visibility when styling the control. If you need this kind of functionality, tell me and I will add a new `DependencyProperty` to hide the scrollbars.

**Comment by Ygsildyr** [comment]
Hi,

Thank you for your reply! It would be nice to have them as separate properties. So far, I've cloned the repository and made this change myself, but we will revert back to using the Nuget package once the update is available.

**Comment by mircea21S** [comment]
Hi,

I've released v2.4.1 which includes 2 properties `VerticalScrollBarVisibility` and `HorizontalScrollBarVisibility` which lets you manipulate the visibility of scrollbars inside the ScrollViewer.

Please close this issue if this works for you or let me know if you have any questions.
